### ISSUE TITLE
Support downloading official watchfaces

### ISSUE THREAD

**Issue by extesy** [Keddnyo/MiDoze#4]
Is it possible to download official watchfaces for these devices similar to how it downloads the firmware?

**Comment by Keddnyo** [comment]
Yes. But we need more specific data to do it. Maybe this features will be added later.

**Comment by extesy** [comment]
I did a little research and _I think_ (not confident) that the url for watchface list looks like https://api.amazfit.com/market/devices/ALL/watch?userid={userid} and it needs a real apptoken. Both can be obtained using https://github.com/argrento/huami-token script but when I do that the request still returns "invalid token" to me. No sure what am I missing.

**Comment by Keddnyo** [comment]
I have already tried this some days ago. I stoled some packages using Burp Suite for Windows. But it really need app token. And now it is impossible to do that without token.

**Comment by Keddnyo** [comment]
Now **[MiDoze 7.0.0](https://github.com/Keddnyo/MiDoze/releases/tag/7.0.0)** supports watch faces. Congratulations!
@extesy  thanks for your idea!

**Comment by extesy** [comment]
Thank you for adding this! It seems that currently it only works with Xiaomi devices. Would it be hard to add Amazfit devices too? Your firmware downloader supports both.

**Comment by Keddnyo** [comment]
It seems to be so hard because request works only with valid token which taken in official app every time. At the next day the previous token is invalid and response says that token is invalid.
