### ISSUE TITLE
App crashes on scroll through dials

### ISSUE THREAD

**Issue by Guusvanmeerveld** [Keddnyo/MiDoze#5]
I don't if this has been fixed in a newer commit already, but with the latest version that's on IzzyOnDroid the app keeps crashing when trying to scroll through the dials tab

**Comment by Guusvanmeerveld** [comment]
This is happening on my Pixel 3a running CalyxOS 3.9.0

**Comment by Keddnyo** [comment]
I use Redmi Note 11 phone. There is no app crash issue in dials tab.

Now I trying to rewrite app's code from scratch using Jetpack Compose framework. Maybe this bug won't happened again.

**Comment by Keddnyo** [comment]
Thank you for your contribution!
Bug fixed in **[MiDoze 7.0.2](https://github.com/Keddnyo/MiDoze/releases/tag/7.0.2)** update.
